(define (require pred)
  (if (not pred)
      (amb)
      'whatever))

(define (member el lst)
  (cond ((null? lst) #f)
        ((eq? el (car lst)) (car lst))
        (else (member el (cdr lst)))))

(define (distinct? items)
  (cond ((null? items) #t)
        ((null? (cdr items)) #t)
        ((member (car items) (cdr items)) #f)
        (else (distinct? (cdr items)))))

(define (multiple-dwelling)
  (let ((baker (amb 1 2 3 4))
        (cooper (amb 1 2 3 4))
        (fletcher (amb 1 2 3 4)))
        ;(miller (amb 1 2 3 4)))
    (distinct? (cons baker (cons cooper (cons fletcher '()))))
    (require (not (= baker 4)))
    (require (not (= cooper 1)))
    (require (not (= fletcher 4)))
    (require (not (= fletcher 1)))
    ;(require (> miller cooper))
    (require (not (or (= (- fletcher cooper) 1)
                      (= (- fletcher cooper) -1))))
    (+ (* baker 1000) (* cooper 100) (* fletcher 10))))
    ;(+ (* baker 1000) (* cooper 100) (* fletcher 10) miller)))

(multiple-dwelling)