(let ((a (random 10))
      (b (random 10)))
  (let* ((c (cons a (cons b 99)))
         (d c))
    (display c)
    (if (= (car c) 10)
        (begin (display 1) (newline)
               (set-car! d (random 10))
               (if (= (car c) 99)
                   (begin (display 11) (newline))
                   (begin (display 12) (newline)
                          (if (= (car (cdr c)) 5)
                              (begin (display 121) (newline))
                              (begin (display 122) (newline))))))
        (begin (display 2) (newline)))))