(define (g)
  (error))
(define (h)
  1)
(let ((a (random 10))
      (b (random 10))
      (c (random 10))
      (f g))
  (if (> a 0)
      (begin (set! f h)
             (f)
             (if (> a 0)
                 (f)
                 'ok))
      'ok))