(define (f x)
  (+ x 1))

(let ((a (random 10))
      (b (random 10)))
  (display a) (newline)
  (display b) (newline)
  (if (< a (f 4))
      (if (< b 5)
          (error 'a)
          'ok)      
      (error 'a)))