;(define (f) (error "error f"))
;(define (g) 'ok)
(let ((a (random 300000))
      (b (random 300000))
      (c 10))
      ;(h f)
      ;(i f))
  ;(display a)
  ;(display b)
  (set! a (random 10000000))
  (if (> (- a c) 5)
      (if (> b 5)
          'ok
          (error "i"))
      'ok))