;(define (f) (error "error f"))
;(define (g) 'ok)
(let ((a (random 3))
      (b (random 3))
      (c 10))
      ;(h f)
      ;(i f))
  ;(display a)
  ;(display b)
  (set! a (random 1))
  (if (> a (+ 1 2 3 4))
      (if (> b 5)
          'ok
          (error "i"))
      'ok))