(letrec ((x 10)
         (test (lambda (a)
                 (letrec ((f (lambda ()
                               a)))
                   (f)
                   (f)
                   (f)))))
  (test 1)
  (test 99))
