#lang scribble/manual
@(require "../oefeningen-bundel-utils.rkt")
          
@title{Lijsten}

@include-section["box-and-pointer.rkt"]
@include-section["oef2.rkt"]
@include-section["lijsten-met-procs.rkt"]
@include-section["my-cons.rkt"]
@include-section["modeloplossing.rkt"]
@include-section["add-to-end.rkt"]
@include-section["my-append.rkt"]
@include-section["reverse.rkt"]
@include-section["last.rkt"]
@include-section["change.rkt"]
@include-section["my-equal.rkt"]
@include-section["sum-lists.rkt"]
@include-section["combine-over-list.rkt"]
@include-section["ex-jan1994.rkt"]
@include-section["ex-jan1999.rkt"]
@include-section["ex1999.rkt"]
@include-section["ex-pjan1994.rkt"]
@include-section["ex-jan1996.rkt"]
@include-section["ex-jan1997.rkt"]
@include-section["ex-jan1999-splits.rkt"]
@include-section["ex-2009.rkt"]
@include-section["geslaagd.rkt"]
@include-section["ex-jan2006.rkt"]
@include-section["ex-jan2008.rkt"]
@include-section["ex-pjan1994-filter.rkt"]
