Abstract Machine Experiments with Scala
* Goal
The goal of this artefact is to experiment with abstract machines and language
semantics with the theoretical framework described by Might, Van Horn and
Johnson (Abstracting Abstract Machines, Abstracting Abstract Control, Pushdown
Control-Flow Analyses).

To see how the framework can be used to build static analyses or define language
semantics, look at src/main/scala/LambdaCalculus.scala.

One of these machines (the Hybrid machine) has been extended with a trace-based Just-In-Time compiler.

* Architecture
To find out about the architecture of the implementation, look at the comments
on the top of Main.scala (src/main/scala/Main.scala). They will bring you to
other parts of the code that are worth seeing.

When doing modification to the source code, you can run the test suite to test
your changes by running =sbt test=. It should take a few minutes to run
everything and will report which tests are failing if there are any.
* Usage
Use sbt to launch the program. Once sbt is launched and has installed the
dependencies, you can perform the following:

#+BEGIN_SRC sh
run -h # Shows the possible options
run -f test/fact.scm # Performs abstract interpretation on fact.scm
run -f test/fact.scm -l Concrete -c # Performs concrete interpretation on fact.scm
run -f test/fact.scm -m AAM # Use the AAM approach (default one is Free)
run -f test/fact.scm -m AAC # Use the AAC approach
run -f test/fact.scm -m AAM -d fact.dot # Output the state graph in fact.dot
run # Launches a REPL that performs interpretation of the input
#+END_SRC

To run the trace-based JIT compiler, choose the Hybrid machine, along with the Concrete lattice (-l Concrete) running concrete interpretation (-c). Some extra execution parameters then become available:

#+BEGIN_SRC sh
run -f test/fact.scm -l Concrete -c -m Hybrid --tracing t --threshold 5 -o all # Run the Hybrid machine on fact.scm, while explicitly enabling tracing, using a hot loop threshold of 5 iterations, and applying all optimisations on the recorded traces.
# These three settings (enabling tracing, using a loop threshold of iterations, and applying all optimisations) correspond with the default parameters.
run -f test/fact.scm -l Concrete -c -m Hybrid --tracing f # Disable tracing
run -f test/fact.scm -l Concrete -c -m Hybrid -o none # Do not apply any optimisations on the traces
run -f test/fact.scm -l Concrete -c -m Hybrid -o 1 # Apply only one specific optimisation (optimisations nr. 1) on the traces.
# Currently, the following optimisations are supported:
# 1 -> constant folding
# 2 -> type specialisation
# 3 -> variable folding
# 4 -> merging actions
# 5 -> remove redundant saves/restores of the environment
# 6 -> remove redundant pushes/pops of continuation frames
#+END_SRC
