#!/bin/bash

trap "exit" INT

for testFile in blur.scm count.scm fib.scm eta.scm fact.scm gcipd.scm inc.scm kcfa2.scm kcfa3.scm mj09.scm mut-rec.scm optimization_test.scm rotate.scm sq.scm ack.scm collatz.scm widen.scm loop2.scm rsa.scm dderiv.scm
do
	for thr in 5 10 2 1 0
	do
		echo "run -m Hybrid -c -l Concrete -f test/$testFile --tracing t -o all --threshold $thr --initial t --switch t" | sbt
	done
done
